// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvdhsjwdcfzozlyrqoqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2ZGhzandkY2Z6b3pseXJxb3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDI5ODIsImV4cCI6MjA2MzMxODk4Mn0.J05rwQOW-t36LlokL4qgDCpeHeXL14RviOx0PRUFXtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);